name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          # macOS first
          - os: macos-latest
            artifact_name: csv-to-links.app
            asset_name: csv-to-links-macos.app
          # Linux second
          - os: ubuntu-latest
            artifact_name: csv-to-links
            asset_name: csv-to-links-linux
          # Windows last
          - os: windows-latest
            artifact_name: csv-to-links.exe
            asset_name: csv-to-links-windows.exe
            msystem: MINGW64
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      # macOS-specific setup
      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install gcc

      # Linux-specific setup
      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc libgl1-mesa-dev xorg-dev

      # Windows-specific setup
      - name: Setup MSYS2 (Windows)
        if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-golang
            mingw-w64-x86_64-cairo
            mingw-w64-x86_64-gcc-libs
            base-devel

      - name: Install Fyne
        run: go install fyne.io/fyne/v2/cmd/fyne@latest

      - name: Build Windows
        if: matrix.os == 'windows-latest'
        shell: msys2 {0}
        run: |
          export PATH="/mingw64/bin:$PATH"
          fyne package -os windows -icon icon.png -name csv-to-links

      - name: Build Linux/macOS
        if: matrix.os != 'windows-latest'
        run: |
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            fyne package -os linux -icon icon.png -name csv-to-links
          else
            fyne package -os darwin -icon icon.png -name csv-to-links
          fi
        shell: bash

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}
          path: ${{ matrix.artifact_name }}
          retention-days: 1

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            */csv-to-links*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
