name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: windows-latest  # Changed to windows-latest for better Windows support
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64

      - name: Install Fyne dependencies
        run: |
          go install fyne.io/fyne/v2/cmd/fyne@latest

      - name: Build Windows
        run: |
          fyne package -os windows -icon icon.png -name csv-to-links

      - name: Build Linux
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc libgl1-mesa-dev xorg-dev
          GOOS=linux GOARCH=amd64 go build -o csv-to-links-linux

      - name: Build macOS
        run: |
          GOOS=darwin GOARCH=amd64 go build -o csv-to-links-macos

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            csv-to-links.exe
            csv-to-links-linux
            csv-to-links-macos
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
